services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  api:
    build: ./backend
    container_name: api
    ports:
      - "8080:8080"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  postgres:
    image: "postgres:16-alpine"
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - PGDATA:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: "keycloak/keycloak:26.0"
    container_name: keycloak
    restart: always
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    command: start-dev --import-realm
    depends_on:
      - postgres
    volumes:
      - ./keycloak/realms/dev-realm.json:/opt/keycloak/data/import/realm-export.json

  redis:
    image: "redis:7.4.1-alpine"
    container_name: redis
    restart: always
    volumes:
      - REDIS_DATA:/data

volumes:
  PGDATA:
  REDIS_DATA:
