services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  api:
    build: ./backend
    container_name: api
    ports:
      - "8080:8080"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  redis:
    image: "redis:7.4.1-alpine"
    container_name: redis
    restart: always
    volumes:
      - REDIS_DATA:/data

volumes:
  REDIS_DATA:
