services:
  postgres:
    image: 'postgres:16-alpine'
    restart: always
    environment:
      POSTGRES_DB: recsec
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - PGDATA:/var/lib/postgresql/data
      - ./dev-environment/postgres/scripts:/docker-entrypoint-initdb.d

  keycloak:
    image: 'keycloak/keycloak:26.0'
    restart: always
    ports:
      - '8081:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    command: start-dev --import-realm
    volumes:
      - ./dev-environment/keycloak/realms:/opt/keycloak/data/import
    depends_on:
      - postgres

  redis:
    image: 'redis:7.4.1-alpine'
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - REDIS_DATA:/data

volumes:
  PGDATA:
  REDIS_DATA:
